//+------------------------------------------------------------------+
//|                                                   QuantTypes.mqh |
//|                       SIGMA Quant - Supabase Export Schema       |
//|                                         https://www.asksigma.com |
//+------------------------------------------------------------------+
#property strict

//+------------------------------------------------------------------+
//| QuantTradeExport                                                 |
//| Matches 'trades' table in Supabase 1:1                           |
//+------------------------------------------------------------------+
struct QuantTradeExport
{
   //--- ID & Metadata
   string            id;                  // UUID (generated by Python if needed, or placeholder)
   long              ticket;              // MT5 Ticket (BigInt)
   string            symbol;
   
   //--- Entry
   string            direction;           // "BUY" or "SELL"
   datetime          entry_time;          // Time of entry
   double            entry_price;
   string            entry_trigger;       // "L1", "FIFTY", "L2"
   
   //--- Exit
   datetime          exit_time;
   double            exit_price;
   string            exit_reason;         // "TP", "SL", "MANUAL", "SWITCH"
   string            result;              // "WIN", "LOSS"
   
   //--- Risk
   double            sl_price;
   double            tp_price;
   double            sl_distance_points;
   double            risk_money;
   double            lot_size;
   
   //--- Outcome
   double            pnl_points;
   double            pnl_money;
   double            r_multiple;
   double            commission;
   double            swap;
   
   //--- Excursions
   double            mae_points;
   double            mfe_points;
   double            edge_ratio;
   
   //--- Duration
   int               bars_held;
   long              duration_seconds;
   
   //--- Entry Zone (WHEN)
   string            zone_id;             // String ID for portability (ulong -> string)
   string            zone_tf;             // "M5", "M15", etc
   int               zone_age_bars;
   int               zone_touch_num;
   double            zone_rel_pos;
   double            zone_size_points;
   
   //--- Cascade (Confluence)
   int               cascade_score;       // Count of aligned TFs
   string            vector_signature;    // V3: 5-TF Vector (H1:H4:D1:W1:MN1) - e.g. "1:1:-1:0:0"
   int               vector_sum;          // V5.0: Explicit Sum of HTF Alignment
   double            target_r;            // V5.0: The R-Multiple target (e.g. 2.5)
   bool              d1_aligned;
   int               buy_votes;
   int               sell_votes;
   string            p_class;             // P1, P2, P3
   
   //--- God Data / Metrics
   int               fractal_depth;       // Russian Doll Score
   double            tf_dominance;        // HTF Strength
   
   //--- Session & Context
   string            session;             // "ASIAN", "LONDON", "NY", "OVERLAP"
   int               day_of_week;         // 0=Sun, 1=Mon...
   int               hour_of_day;         // 0-23
   double            atr_at_entry;        // Volatility context
   
   //--- Quant 2.0 Physics Tags
   int               sequence_index;      // N_seq
   string            lifecycle_phase;     // Probe, Flow, Decay
   string            landing_type;        // LIFO/FIFO
   
   //--- Quantum Audit V2: Risk & Capital Foundation
   double            base_risk_pct;       // Core risk % from settings (e.g., 1.0%)
   double            touch_risk_pct;      // Actual risk % after T-Touch adjustment
   int               leverage;            // Account leverage at entry
   double            capital_at_entry;    // Account balance at entry (base currency)
   
   //--- Quantum Audit V2: Trade Management Intelligence
   double            trailing_sl_locked_pts; // Points locked in by trailing stop
   bool              be_activated;        // Break-Even / Survival Guard triggered?
   
   
    //--- Russian Doll Protocol (V5.9)
    string            layer_1_tide;        // General's Tide (MN1/W1)
    string            layer_2_wind;        // Officer's Wind (D1/H4)
    string            layer_3_trap;        // Sniper's Trap (H1/M30)
    string            layer_4_trigger;     // Trigger Level (M5/M1)
    
    ulong             anchor_id;           // Primary Origin of Flow
    ulong             outpost_id;          // Successor / Forward Protection
    string            bridge_state;        // Recursive Handshake (H4/H1/M30)
    
    bool              narrative_conflict_blocked; // V5.9 Narrative Shield
    
    // ML Confluence
    string            aligned_zones_json;  // JSON string of aligned zones array
    string            tfs_aligned_json;    // JSON string of aligned TFs ["H1", "H4"]
    bool              direction_correct;   // Filled after trade close
    
    //--- Constructor
    QuantTradeExport() 
    { 
       ZeroMemory(this); 
       // Initialize strings
       id = ""; symbol = ""; direction = ""; entry_trigger = "";
       exit_reason = ""; result = ""; zone_id = ""; zone_tf = "";
       p_class = ""; session = ""; lifecycle_phase = ""; landing_type = "";
       aligned_zones_json = "[]"; tfs_aligned_json = "[]";
       layer_1_tide = ""; layer_2_wind = ""; layer_3_trap = ""; layer_4_trigger = "";
       bridge_state = "";
       anchor_id = 0; outpost_id = 0;
    }
};

//+------------------------------------------------------------------+
//| ZoneLogEntry                                                      |
//| Matches 'zones' table in Supabase 1:1                             |
//+------------------------------------------------------------------+
struct ZoneLogEntry
{
   string            event_type;           // CREATED/TOUCHED/SURVIVED/BULLDOZED
   string            zone_id;
   string            tf;
   string            direction;
   
   // Price Levels
   double            l1_price;
   double            l2_price;
   double            fifty_percent;
   
   // Pattern Components
   double            first_barrier_price;
   datetime          first_barrier_time;
   double            second_barrier_price;
   datetime          second_barrier_time;
   
   // Lifecycle
   datetime          created_time;
   datetime          event_time;
   datetime          l1_touch_time;
   datetime          fifty_touch_time;
   datetime          l2_touch_time;
   datetime          invalidation_time;
   
   // Touch Tracking
   bool              l1_touched;
   bool              fifty_touched;
   bool              l2_touched;
   
   // Outcome
   string            outcome;              // UNTOUCHED/SURVIVED/BULLDOZED
   int               age_at_first_touch;
   int               age_at_invalidation;
   string            touch_depth_at_outcome; // T0/T1/T2/T3
   
   // Context
   int               sequence_index;
   string            htf_parent_id;
   bool              has_htf_alignment;
   bool              has_narrative_parent;
   bool              has_control_parent;
   
   // Phase 0.5B - MFE Context Fields
   string            session_at_touch;      // ASIAN, LONDON, OVERLAP, NY, OFF_HOURS
   string            touch_quarter;         // Q1, Q2, Q3, Q4
   int               bars_after_t1;         // Bars from T1 (L1 touch) to death
   int               bars_after_t2;         // Bars from T2 (50% touch) to death
   int               bars_after_t3;         // Bars from T3 (L2 touch) to death
   double            mfe_pips;              // Max Favorable Excursion (R-multiple numerator)
   double            mae_pips;              // Max Adverse Excursion (drawdown)
   double            zone_size_pips;        // Zone size for R-multiple calculation
   
   // Phase 1 Physics (Time-to-Event)
   datetime          mfe_time;              // When MFE occurred
   datetime          mae_time;              // When MAE occurred
   
   // Metadata
   string            dataset_type;         // EXPLORATION/VALIDATION/LIVE
   
   // Constructor
   ZoneLogEntry() 
   { 
      ZeroMemory(this); 
      event_type = ""; zone_id = ""; tf = ""; direction = "";
      outcome = ""; touch_depth_at_outcome = "T0";
      htf_parent_id = ""; session_at_touch = ""; touch_quarter = "";
      dataset_type = "EXPLORATION";
   }
};
