"""Generate mt5/Include/<system>_system/<system>_version.mqh from git state.

Pre-compile step for any Baysix trader/emitter EA: stamps the exact git sha /
branch / dirty-flag / build-time into a header the EA prints on OnInit, so every
test report and live chart traces back to the precise code that produced it
(closes the "which version made this number?" trust gap — the same failure mode
that hid the ORB look-ahead).

System-agnostic: pass the system prefix as the sole argument. Emits
<SYS>_GIT_SHA / <SYS>_GIT_BRANCH / <SYS>_GIT_DIRTY / <SYS>_BUILD_TIME defines.

Run before every headless compile, e.g.:
    python research/code/infra/gen_version.py fob
    python research/code/infra/gen_version.py brc
"""
from __future__ import annotations
import sys
import subprocess
from datetime import datetime, timezone, timedelta
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
MYT = timezone(timedelta(hours=8))  # Malaysia time, matches repo convention


def _git(*args: str) -> str:
    return subprocess.check_output(["git", *args], cwd=REPO, text=True).strip()


def gen(system: str) -> Path:
    sys_lc = system.lower()
    SYS = sys_lc.upper()
    out = REPO / "mt5" / "Include" / f"{sys_lc}_system" / f"{sys_lc}_version.mqh"
    if not out.parent.exists():
        raise SystemExit(f"[gen_version] no such include dir: {out.parent.relative_to(REPO)}")

    sha = _git("rev-parse", "--short", "HEAD")
    branch = _git("rev-parse", "--abbrev-ref", "HEAD")
    dirty = bool(_git("status", "--porcelain"))
    built = datetime.now(MYT).strftime("%Y-%m-%d %H:%M:%S MYT")

    guard = f"{SYS}_VERSION_MQH"
    body = f"""//+------------------------------------------------------------------+
//|                                              {sys_lc}_version.mqh  |
//|  AUTO-GENERATED by research/code/infra/gen_version.py {sys_lc}.      |
//|  DO NOT EDIT BY HAND and DO NOT rely on it being current unless    |
//|  the generator was run immediately before this compile.            |
//|  Git SHA + dirty flag are the real provenance; a number produced   |
//|  by a DIRTY tree is NOT reproducible -> treat as exploratory.      |
//+------------------------------------------------------------------+
#ifndef {guard}
#define {guard}

#define {SYS}_GIT_SHA     "{sha}"
#define {SYS}_GIT_BRANCH  "{branch}"
#define {SYS}_GIT_DIRTY   {"true" if dirty else "false"}
#define {SYS}_BUILD_TIME  "{built}"

#endif // {guard}
"""
    out.write_text(body, encoding="utf-8")
    flag = " (DIRTY)" if dirty else ""
    print(f"[gen_version] {sys_lc}: {sha}@{branch}{flag} -> {out.relative_to(REPO)}")
    return out


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: python research/code/infra/gen_version.py <system>   (e.g. fob | brc)")
    gen(sys.argv[1])


if __name__ == "__main__":
    main()
