"""Generate mt5/Include/brc_system/brc_version.mqh from git state.

Pre-compile step for the BRC trader EA: stamps the exact git sha / branch /
dirty-flag / build-time into a header the EA prints on OnInit, so every test
report and live chart traces back to the precise code that produced it
(closes the "which version made this number?" trust gap — the same failure
mode that hid the ORB look-ahead).

Run before every headless compile:  python research/code/infra/gen_brc_version.py
"""
from __future__ import annotations
import subprocess
from datetime import datetime, timezone, timedelta
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
OUT = REPO / "mt5" / "Include" / "brc_system" / "brc_version.mqh"
MYT = timezone(timedelta(hours=8))  # Malaysia time, matches repo convention


def _git(*args: str) -> str:
    return subprocess.check_output(["git", *args], cwd=REPO, text=True).strip()


def main() -> None:
    sha = _git("rev-parse", "--short", "HEAD")
    branch = _git("rev-parse", "--abbrev-ref", "HEAD")
    dirty = bool(_git("status", "--porcelain"))
    built = datetime.now(MYT).strftime("%Y-%m-%d %H:%M:%S MYT")

    body = f"""//+------------------------------------------------------------------+
//|                                                  brc_version.mqh  |
//|  AUTO-GENERATED by research/code/infra/gen_brc_version.py.         |
//|  DO NOT EDIT BY HAND and DO NOT rely on it being current unless    |
//|  the generator was run immediately before this compile.            |
//|  Git SHA + dirty flag are the real provenance; a number produced   |
//|  by a DIRTY tree is NOT reproducible -> treat as exploratory.      |
//+------------------------------------------------------------------+
#ifndef BRC_VERSION_MQH
#define BRC_VERSION_MQH

#define BRC_GIT_SHA     "{sha}"
#define BRC_GIT_BRANCH  "{branch}"
#define BRC_GIT_DIRTY   {"true" if dirty else "false"}
#define BRC_BUILD_TIME  "{built}"

#endif // BRC_VERSION_MQH
"""
    OUT.write_text(body, encoding="utf-8")
    flag = " (DIRTY)" if dirty else ""
    print(f"[gen_brc_version] {sha}@{branch}{flag} -> {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
